# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
