# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='null', max_length=100)),
                ('category', models.CharField(default='null', max_length=50)),
                ('viewed', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User_app.User')),
            ],
        ),
    ]
