# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0011_profile_picture'),
        ('User_app', '0012_auto_20170902_2321'),
    ]

    operations = [
    ]
