# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0013_merge_20170903_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hometown',
        ),
    ]
