# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
