# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20170831_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='review',
            name='api_Movie_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='backdrop_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='poster_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
