# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_auto_20170831_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
