# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_Movie_code', models.CharField(max_length=100)),
            ],
        ),
    ]
