# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_auto_20170903_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
