# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0006_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='episode_review',
            field=models.ManyToManyField(related_name='episodes', to='movieApp.EpisodeReview'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='movie_review',
            field=models.ManyToManyField(related_name='movies', to='movieApp.MovieReview'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='tv_review',
            field=models.ManyToManyField(related_name='tvs', to='movieApp.TVReview'),
        ),
    ]
