# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0007_auto_20170904_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodereview',
            old_name='backdrop_path',
            new_name='still_path',
        ),
        migrations.AddField(
            model_name='episodereview',
            name='episode',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodereview',
            name='season',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
